import os
import uuid
import shutil
from pathlib import Path
from fastapi import UploadFile, HTTPException

TEMP_DIR = Path(__file__).parent.parent / "temp"
REPORTS_DIR = Path(__file__).parent.parent / "reports"


def ensure_dirs() -> None:
    """Create temp/ and reports/ directories if they don't exist."""
    TEMP_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)


async def save_upload(file: UploadFile, session_id: str) -> Path:
    """
    Save an uploaded MP3 file to temp/{session_id}.mp3.
    Returns the path to the saved file.
    Raises HTTPException 400 if the file is not an MP3.
    """
    # Basic MIME / extension validation
    filename = file.filename or ""
    content_type = file.content_type or ""
    if not (
        filename.lower().endswith(".mp3")
        or "audio/mpeg" in content_type
        or "audio/mp3" in content_type
    ):
        raise HTTPException(
            status_code=400,
            detail="Only MP3 audio files are accepted.",
        )

    dest = TEMP_DIR / f"{session_id}.mp3"
    with dest.open("wb") as out:
        shutil.copyfileobj(file.file, out)

    return dest


def delete_temp(session_id: str) -> None:
    """Remove the temporary MP3 file for a session (if it exists)."""
    path = TEMP_DIR / f"{session_id}.mp3"
    try:
        path.unlink(missing_ok=True)
    except Exception:
        pass  # Best-effort cleanup


def format_feedback_txt(
    feedback: dict,
    question: str,
    transcript: str,
    session_id: str,
) -> str:
    """
    Format the structured feedback dict into a human-readable .txt report string.
    """
    from datetime import datetime

    now = datetime.now()
    date_str = now.strftime("%d %b %Y")
    time_str = now.strftime("%I:%M %p")

    scores = feedback.get("scores", {})
    score_lines = "\n".join(
        f"  {label.capitalize():<13}: {info['score']}/10 — {info['feedback']}"
        for label, info in scores.items()
    )

    def bullet_list(items: list[str]) -> str:
        return "\n".join(f"  • {item}" for item in items)

    lines = f"""\
================================================
        INTERVIEW COACH — FEEDBACK REPORT
================================================

Question:
\"{question}\"

Date: {date_str}  |  Time: {time_str}
Session: {session_id[:8]}

------------------------------------------------
OVERALL SCORE: {feedback.get('overall_score', 'N/A')}/10
------------------------------------------------

SCORES
{score_lines}

------------------------------------------------
✅ WHAT YOU DID WELL
{bullet_list(feedback.get('what_went_well', []))}

📌 WHAT YOU MISSED
{bullet_list(feedback.get('what_was_missed', []))}

💡 HOW TO IMPROVE
{bullet_list(feedback.get('improvements', []))}

------------------------------------------------
YOUR TRANSCRIPT
  \"{transcript}\"

------------------------------------------------
🏆 IDEAL ANSWER
  \"{feedback.get('ideal_answer', '')}\"

================================================
              Generated by Interview Coach
================================================
"""
    return lines


def save_report_txt(formatted_str: str, session_id: str) -> Path:
    """Save the formatted report string to reports/{session_id}_feedback.txt."""
    ensure_dirs()
    path = REPORTS_DIR / f"{session_id}_feedback.txt"
    path.write_text(formatted_str, encoding="utf-8")
    return path


def get_report_path(session_id: str) -> Path:
    """Return the path to a saved report, raise 404 if not found."""
    path = REPORTS_DIR / f"{session_id}_feedback.txt"
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Report not found for session {session_id}.",
        )
    return path
